![data-x](http://oi64.tinypic.com/o858n4.jpg)

---
# NumPy Data X 

**Author:** Alexander Fred-Ojala & Ikhlaq Sidhu

**License Agreement:** Feel free to do whatever you want with this code

___

# Introduction to NumPy

# What is NumPy:  

NumPy stands for Numerical Python and it is the fundamental package for scientific computing with Python. It is a package that lets you efficiently store and manipulate numerical arrays. It contains among other things:

* a powerful N-dimensional array object
* sophisticated (broadcasting) functions
* tools for integrating C/C++ and Fortran code
* useful linear algebra, Fourier transform, and random number capabilities


# NumPy contains an array object that is "fast"


<img src="https://github.com/ikhlaqsidhu/data-x/raw/master/imgsource/threefundamental.png">


It stores:
* location of a memory block (allocated all at one time)
* a shape (3 x 3 or 1 x 9, etc)
* data type / size of each element

The core feauture that NumPy supports is its multi-dimensional arrays. In NumPy, dimensions are called axes and the number of axes is called a rank.

In [1]:
# written for Python 3.6
import numpy as np

In [2]:
np.__version__ # made for v. 1.14.2

'1.14.2'


## Creating a NumPy Array: - 
### 1. Simplest possible: We use a list as an argument input in making a NumPy Array


In [3]:
# Create array from Python list
list1 = [1, 2, 3, 4]
data = np.array(list1)
data

array([1, 2, 3, 4])

In [4]:
# Find out object type
type(data)

numpy.ndarray

In [5]:
# See data type that is stored in the array
data.dtype

dtype('int64')

In [6]:
# The data types are specified for the full array, if we store
# a float in an int array, the float will be up-casted to an int
data[0] = 3.14159
print(data)

[3 2 3 4]


In [7]:
# NumPy converts to most logical data type
list2 = [1.2, 2, 3, 4]
data2 = np.array(list2)
print(data2)
print(data2.dtype) # all values will be converted to floats if we have one

[1.2 2.  3.  4. ]
float64


In [8]:
# We can manually specify the datatype
list3 = [1, 2, 3]
data3 = np.array(list3, dtype=str) #manually specify data type


In [9]:
print(data3)
print(data3.dtype)

['1' '2' '3']
<U1


In [10]:
# lists can also be much longer
list4 = range(100001)
data = np.array(list4)
data

array([     0,      1,      2, ...,  99998,  99999, 100000])

In [11]:
len(data) # to see the length of the full array

100001

In [13]:
#data = np.array(1,2,3,4, 5,6,7,8,9) # wrong
data = np.array([1,2,3,4,5,6,7,8,9]) # right
data

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
# see documentation, the first keyword is the object to be passed in
np.array?

More info on data types can be found here:
https://docs.scipy.org/doc/numpy-1.13.0/user/basics.types.html

# Accessing elements: Slicing and indexing

In [15]:
# Similar to indexing and slicing Python lists:
print(data)

[1 2 3 4 5 6 7 8 9]


In [16]:
print (data[0:3])

[1 2 3]


In [17]:
print (data[3:])

[4 5 6 7 8 9]


## Arrays are like lists, but different
NumPy utilizes efficient pointers to a location in memory and it will store the full array in memory. Lists on the other hand are pointers to many different objects in memory.

In [19]:
# Slicing returns a view in Numpy, 
# and not a copy as is the case with Python lists


data = np.array(range(10))
view = data[0:3]
view

array([0, 1, 2])

In [20]:
l = list(range(10))
copy = l[0:3]
copy

[0, 1, 2]

In [21]:
copy[0] = 99
view[0] = 99
print(copy)
print(view)

[99, 1, 2]
[99  1  2]


In [22]:
print('Python list:',l) # has not changed

Python list: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [23]:
print('NumPy array:',data) # has changed

NumPy array: [99  1  2  3  4  5  6  7  8  9]


# Arrays are a lot faster than lists

In [25]:
# Arrays are faster and more efficient than lists

x = list(range(100000))
y = [i**2 for i in x]
print (y[0:5])

[0, 1, 4, 9, 16]


In [26]:
# Time the operation with some IPython magic command
print('Time for Python lists:')
%timeit [i**2 for i in x]

Time for Python lists:
20.4 ms ± 221 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [27]:
z = np.array(x)

In [29]:
print('Time for NumPy arrays:')
%timeit z**2

Time for NumPy arrays:
38.5 µs ± 163 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


# Universal functions
A function that is applied on an `ndarray` in an element-by-element fashion. Several universal functions can be found the NumPy documentation here:
https://docs.scipy.org/doc/numpy-1.13.0/reference/ufuncs.html

In [30]:
# Arrays are different than lists in another way:
# x and y are lists

x = list(range(5))
y = list(range(5,10))
print ("list x = ", x)
print ("list y = ", y)

list x =  [0, 1, 2, 3, 4]
list y =  [5, 6, 7, 8, 9]


In [31]:
print ("x + y = ", x+y)

x + y =  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [32]:
# now lets try with NumPy arrays:
xn = np.array(x)
yn = np.array(y)
print ('np.array xn =', xn)
print ('np.array xn =', yn)

np.array xn = [0 1 2 3 4]
np.array xn = [5 6 7 8 9]


In [33]:
print ("xn + yn = ", xn + yn)

xn + yn =  [ 5  7  9 11 13]


In [35]:
# An array is a sequence that can be manipulated easily
# An arithmatic operation is applied to each element individually
# When two arrays are added, they must have the same size 
# (otherwise they might be broadcasted)

print (3 * xn)

[ 0  3  6  9 12]


### Creating arrays with 2 axis:


In [36]:
# This list has two dimensions
list3 = [[1, 2, 3],
         [4, 5, 6]]
list3 # nested list

[[1, 2, 3], [4, 5, 6]]

In [37]:
# data = np.array([[1, 2, 3], [4, 5, 6]])
data = np.array(list3)
data

array([[1, 2, 3],
       [4, 5, 6]])

# Attributes of a multidim array

In [38]:
print ('Shape:',data.shape)
print('Size:', data.size)

Shape: (2, 3)
Size: 6


In [39]:
# You can also transpose an array Matrix with either np.transpose(arr)
# or arr.T
print ('Transpose:')
data.T

# print (list3.T) # note, this would not work

Transpose:


array([[1, 4],
       [2, 5],
       [3, 6]])

# Other ways to create NumPy arrays

In [40]:
# np.arange() is similar to built in range()
# Creates array with a range of consecutive numbers
# starts at 0 and step=1 if not specified. Exclusive of stop.

np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [41]:
#Array increasing from start to end: np.arange(start, end)
np.arange(10, 20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [42]:
# Array increasing from start to end by step: np.arange(start, end, step)
# The range always includes start but excludes end
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [43]:
# Returns a new array of specified size, filled with zeros.
array=np.zeros((2,5))
array

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [44]:
#Returns a new array of specified size, filled with ones.
array=np.ones((2,5), dtype=np.int)
array

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [45]:
# Returns the identity matrix of specific squared size
array = np.eye(5)
array

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## Some useful indexing strategies

### There are two main types of indexing: Integer and Boolean

In [46]:
x = np.array([[1, 2], [3, 4], [5, 6]]) 
x

array([[1, 2],
       [3, 4],
       [5, 6]])

#### Integer indexing

In [47]:
# first element is  the row, 2nd element is the column
print(x[1,0])

3


In [48]:
print(x[1,:]) # all rows after first, all columns

[3 4]


### Boolean indexing

In [49]:
print('Comparison operator, find all values greater than 3:\n')
print(x>3)

Comparison operator, find all values greater than 3:

[[False False]
 [False  True]
 [ True  True]]


In [50]:
print('Boolean indexing, only extract elements greater than 3:\n')
print(x[x>3])

Boolean indexing, only extract elements greater than 3:

[4 5 6]


## Extra NumPy array methods

In [51]:
# Reshape is used to change the shape
a = np.arange(0, 15)

print('Original:',a)
a = a.reshape(3, 5)
# a = np.arange(0, 15).reshape(3, 5)  # same thing

print ('Reshaped:')
print(a)


Original: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
Reshaped:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [52]:
# We can also easily find the sum, min, max, .. are easy
print (a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [53]:
print ('Sum:',a.sum())
print('Min:', a.min())
print('Max:', a.max())

Sum: 105
Min: 0
Max: 14


In [54]:
print ('Sum along columns:',a.sum(axis=0))
print ('Sum along rows:',a.sum(axis=1))

# Note here axis specifies what dimension to "collapse"

Sum along columns: [15 18 21 24 27]
Sum along rows: [10 35 60]


## Arrray Axis
<img src= "https://github.com/ikhlaqsidhu/data-x/raw/master/imgsource/anatomyarray.png">



To get the cumulative product:

In [55]:
print (np.arange(1, 10))
print (np.cumprod(np.arange(1, 10)))

[1 2 3 4 5 6 7 8 9]
[     1      2      6     24    120    720   5040  40320 362880]


To get the cumulative sum:

In [56]:
print (np.arange(1, 10))
np.cumsum((np.arange(1, 10)))

[1 2 3 4 5 6 7 8 9]


array([ 1,  3,  6, 10, 15, 21, 28, 36, 45])

Creating a 3D array:

In [57]:
a = np.arange(0, 96).reshape(2, 6, 8)
print(a)

[[[ 0  1  2  3  4  5  6  7]
  [ 8  9 10 11 12 13 14 15]
  [16 17 18 19 20 21 22 23]
  [24 25 26 27 28 29 30 31]
  [32 33 34 35 36 37 38 39]
  [40 41 42 43 44 45 46 47]]

 [[48 49 50 51 52 53 54 55]
  [56 57 58 59 60 61 62 63]
  [64 65 66 67 68 69 70 71]
  [72 73 74 75 76 77 78 79]
  [80 81 82 83 84 85 86 87]
  [88 89 90 91 92 93 94 95]]]


# More ufuncs and Basic Operations

One of the coolest parts of NumPy is the ability for you to run mathematical operations on top of arrays. Here are some basic operations:

In [58]:
a = np.arange(11, 21)
b = np.arange(0, 10)
print ("a = ",a)
print ("b = ",b)
print (a + b)

a =  [11 12 13 14 15 16 17 18 19 20]
b =  [0 1 2 3 4 5 6 7 8 9]
[11 13 15 17 19 21 23 25 27 29]


In [59]:
a * b

array([  0,  12,  26,  42,  60,  80, 102, 126, 152, 180])

In [60]:
a ** 2

array([121, 144, 169, 196, 225, 256, 289, 324, 361, 400])

You can even do things like matrix operations

In [61]:
# Matrix multiplication
c = np.arange(1,5).reshape(2,2)
print ("c = \n", c)
print()
d = np.arange(5,9).reshape(2,2)
print ("d = \n", d)

c = 
 [[1 2]
 [3 4]]

d = 
 [[5 6]
 [7 8]]


In [62]:
np.matmul(d,c)

array([[23, 34],
       [31, 46]])

# Random numbers

In [63]:
# Radom numbers
np.random.seed(0)  # set the seed to zero for reproducibility
print(np.random.uniform(1,5,10))   # 10 random uniform numbers from 1 to 5

[3.19525402 3.86075747 3.4110535  3.17953273 2.6946192  3.58357645
 2.75034885 4.567092   4.85465104 2.53376608]


In [64]:
print (np.random.randn(8).reshape(2,4)) #8 random 0-1 in a 2 x 4 array

[[ 0.14404357  1.45427351  0.76103773  0.12167502]
 [ 0.44386323  0.33367433  1.49407907 -0.20515826]]


If you want to learn more about "random" numbers in NumPy go to: https://docs.scipy.org/doc/numpy-1.12.0/reference/routines.random.html

# Trignometric functions

In [65]:
# linspace: Create an array with numbers from a to b 
# with n equally spaced numbers (inclusive)

data = np.linspace(0,10,5)
print (data)

[ 0.   2.5  5.   7.5 10. ]


In [69]:
from numpy import pi
#x = np.linspace(0,pi, 3)
x = np.array([0,np.pi/2,np.pi])
print('x = ', x)
print()
print ("sin(x) = ", np.sin(x))

x =  [0.         1.57079633 3.14159265]

sin(x) =  [0.0000000e+00 1.0000000e+00 1.2246468e-16]


In [67]:
# flatten matrices using ravel()
x = np.array(range(24))
x = x.reshape(4,6)
print('Original:\n',x)
print()
x = x.ravel() # make it flat
print ('Flattened:\n',x)

Original:
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]

Flattened:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


3.141592653589793